#!/bin/sh
#
# Testscript
#

i=11
line='*******************************************************************************'

clear
echo "$line"
./rga -r Racelogs/$i.txt Saves/00_Init.csv Saves/$i.csv
echo "$line"
./rga -u Saves/$i.csv Saves/$i.csv.updated
echo "$line"
#read A

while [ "$i" -lt 28 ]; do
	j=$((i+1))
	clear
	echo "$line"
	./rga -r Racelogs/$j.txt Saves/$i.csv Saves/$j.csv
	echo "$line"
	./rga -u Saves/$j.csv Saves/$j.csv.updated
	echo "$line"
#	read A
	i=$j
done

clear
echo "$line"
./rga -f Saves/$i.csv
echo "$line"
