#!/bin/sh
#
# Testscript
#

i=11
line='*******************************************************************************'

#./rlc-gtl-auswertung -i Saves/00_Init.csv

clear
echo "$line"
./rlc-gtl-auswertung -r Racelogs/$i.txt Saves/00_Init.csv Saves/$i.csv
echo "$line"
./rlc-gtl-auswertung -u Saves/$i.csv
echo "$line"
#read A

while [ "$i" -lt 28 ]; do
	j=$((i+1))
	clear
	echo "$line"
	./rlc-gtl-auswertung -r Racelogs/$j.txt Saves/$i.csv Saves/$j.csv
	echo "$line"
	./rlc-gtl-auswertung -u Saves/$j.csv
	echo "$line"
#	read A
	i=$j
done
